services:
  db:
    image: postgres:16.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"

  test_web:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - .env.test
    depends_on:
      - db
    command:
      [
        "sh",
        "-c",
        "until pg_isready -h db -p 5432 -U ${POSTGRES_USER}; do sleep 1; done && alembic upgrade head && pytest -v --maxfail=5",
      ]
# && alembic upgrade head
